"""Application services for the governed AI Monitor pipeline."""

from .ablation import classify_ablation_signal_state
from .contracts import AiMonitorAuthority, AiMonitorStageResult
from .event_gate import (
    EventGateService,
    market_risk_event_gate_snapshot,
    market_risk_event_snapshot,
    utc_event_iso,
)
from .macro_regime import MacroRegimeService
from .market_features import MarketFeatureService, realtime_feature_payload
from .news_scoring import (
    NewsScoringService,
    aggregate_news_candidates,
    configured_indicator_policy,
    indicator_group,
    match_configured_indicators,
    multi_timeframe_technical_snapshot,
    news_actionability_snapshot,
    news_event_bursts,
    news_event_cluster_id,
    resolved_news_event_cluster_id,
    select_directional_candidates_with_technical_context,
)
from .opportunity_generation import (
    OpportunityGenerationService,
    annotate_event_cluster_selection,
    filter_monitored_candidates,
    filter_technically_admissible_candidates,
    fresh_candidate_news_ids,
    merge_candidate_sources,
    prepare_candidate_news_triggers,
    strongest_candidate_per_symbol,
    technical_market_candidates,
)
from .opportunity_projection import (
    OpportunityProjectionError,
    OpportunityProjectionLagging,
    OpportunityProjectionService,
    OpportunityProjectionUnavailable,
)
from .prediction_settlement import (
    PredictionSettlementService,
    adaptive_exit_precedes,
    historical_closed_settlement_price,
    historical_settlement_price,
    prediction_adaptive_path_exit,
    prediction_cost_breakdown,
    prediction_cost_settings,
    prediction_estimated_cost_bps,
    prediction_net_outcome,
    prediction_outcome,
    prediction_path_metrics,
    prediction_price_barrier_exit,
    prediction_score_exit_price,
    prediction_score_exit_signal,
    prediction_settlement_cost_config,
    prediction_soft_exit_policy,
    readiness_cost_config,
    settlement_exit_subreason,
    virtual_risk_plan_snapshot,
)

__all__ = [
    "AiMonitorAuthority",
    "AiMonitorStageResult",
    "classify_ablation_signal_state",
    "EventGateService",
    "market_risk_event_gate_snapshot",
    "market_risk_event_snapshot",
    "MacroRegimeService",
    "MarketFeatureService",
    "NewsScoringService",
    "aggregate_news_candidates",
    "configured_indicator_policy",
    "indicator_group",
    "OpportunityGenerationService",
    "annotate_event_cluster_selection",
    "filter_monitored_candidates",
    "filter_technically_admissible_candidates",
    "fresh_candidate_news_ids",
    "merge_candidate_sources",
    "news_event_bursts",
    "news_actionability_snapshot",
    "news_event_cluster_id",
    "match_configured_indicators",
    "multi_timeframe_technical_snapshot",
    "OpportunityProjectionError",
    "OpportunityProjectionLagging",
    "OpportunityProjectionService",
    "OpportunityProjectionUnavailable",
    "PredictionSettlementService",
    "adaptive_exit_precedes",
    "historical_closed_settlement_price",
    "historical_settlement_price",
    "prediction_adaptive_path_exit",
    "prediction_cost_breakdown",
    "prediction_cost_settings",
    "prediction_estimated_cost_bps",
    "prediction_net_outcome",
    "prediction_outcome",
    "prediction_path_metrics",
    "prediction_price_barrier_exit",
    "prediction_score_exit_price",
    "prediction_score_exit_signal",
    "prediction_settlement_cost_config",
    "prediction_soft_exit_policy",
    "prepare_candidate_news_triggers",
    "realtime_feature_payload",
    "readiness_cost_config",
    "settlement_exit_subreason",
    "virtual_risk_plan_snapshot",
    "resolved_news_event_cluster_id",
    "select_directional_candidates_with_technical_context",
    "strongest_candidate_per_symbol",
    "technical_market_candidates",
    "utc_event_iso",
]
